
App\Entity\Location:
  properties:

    latitude:
      - NotBlank:
          groups: [ 'new','edit' ]
      - Regex:
          pattern: '/^-?\d{1,3}\.\d{1,7}$/'
          message: 'Enter a valid latitude.'
          groups: [ 'new', 'edit' ]
    longitude:
      - NotBlank:
          groups: [ 'new', 'edit' ]
      - Regex:
          pattern: '/^-?\d{1,3}\.\d{1,7}$/'
          message: 'Enter a valid longitude.'
          groups: [ 'new', 'edit' ]
    country:
      - NotBlank:
          groups: [ 'create', 'edit' ]
